### ISSUE TITLE
Setup JupyterLite deployment in gh-pages

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/project.lecture-wasm#1]
We should build a jupyterlite deployment in this repo and host it on `gh-pages`

- [ ] build jupyterlite for gh-pages
- [ ] configure a custom environment

https://jupyterlite.readthedocs.io/en/latest/#build-your-own-jupyterlite

**Comment by mmcky** [comment]
thanks @Smit-create sounds like the `wasm` testing is going well. In the meeting you mentioned a `jupyterlite` environment. Is that local or have you managed to load it up on gh-pages?

**Comment by Smit-create** [comment]
I have setup a CI, if that doesn't work, we need to enable deployment option in the settings of this repository.

**Comment by Smit-create** [comment]
@mmcky Can you please setup the URL and enable the deploy option? Once that is done in settings, CI will pass and the lectures will be live. Thanks!

**Comment by mmcky** [comment]
@Smit-create does this need a branch `gh-pages`?

**Comment by mmcky** [comment]
@Smit-create I have also given you admin rights to this repo

**Comment by mmcky** [comment]
thanks @Smit-create working nicely now

https://quantecon.github.io/project.lecture-wasm/lab/index.html
